const express=require("express")
const cors=require("cors")
const app =express()
const exp = require("constants")
const subcatRoute = require("./routes/subcategory")
const productRoute = require("./routes/Product")
require("dotenv").config()
const categoryRoute = require("./routes/category")
const registerUser = require("./routes/register")
app.use(cors())
app.use(express.json())
app.use(express.static("catPic"))
// app.use(express.static("subcatPics"))
app.use(express.static("subcatPics"))
app.use(express.static("productPic"))
app.use("/api/v1",categoryRoute)
app.use("/api/v1",subcatRoute)
app.use("/api/v1",productRoute)
app.use("/api/v1",registerUser)
app.listen(3000,()=>{
    console.log(`app listening at port 3000`)
})